apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ${NAME_AGENT_CSR}
spec:
  request: ${AGENT_CSR}
  signerName: ${SIGNER_NAME}
  usages:
  - digital signature
  - key encipherment
  - server auth
