{{- if not .Values.bouncer.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crowdsec-spoa-bouncer.secretName" . }}
  labels:
    {{- include "crowdsec-spoa-bouncer.labels" . | nindent 4 }}
type: Opaque
data:
  apiKey: {{ include "crowdsec-spoa-bouncer.apiKey" . | b64enc }}
{{- end }}
