apiVersion: v1
kind: Service
metadata:
  name: {{ include "crowdsec-spoa-bouncer.fullname" . }}
  labels:
    {{- include "crowdsec-spoa-bouncer.labels" . | nindent 4 }}
    {{- with .Values.bouncer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.bouncer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.bouncer.service.type }}
  selector:
    {{- include "crowdsec-spoa-bouncer.selectorLabels" . | nindent 4 }}
  ports:
    - name: spoa
      port: {{ .Values.bouncer.spoa.port }}
      targetPort: spoa
      protocol: TCP
    {{- if .Values.bouncer.metrics.enabled }}
    - name: metrics
      port: {{ .Values.bouncer.spoa.metricsPort }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
