# vim: set ft=gotmpl:
---

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}
spec:
  forwardAuth:
    address: http://{{ .Release.Name }}-service.{{ .Release.Namespace }}/api/v1/forwardAuth
