# vim: set ft=gotmpl:
---

{{- if .Values.agent.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-agent-service
  labels:
    app: {{ .Release.Name }}-agent-service
    {{- with .Values.agent.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.agent.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.agent.service.type }}
  {{- with .Values.agent.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.agent.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.agent.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.agent.service.type "LoadBalancer") (eq .Values.agent.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.agent.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: metrics
  selector:
    k8s-app: {{ .Release.Name }}
    type: agent
    version: v1
{{- end -}}
