{{- if .Values.agent.enabled }}

{{- if index .Values.config "simulation.yaml" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-simulation
data:
  simulation.yaml: |
{{ printf "%+v" (index .Values.config "simulation.yaml") | indent 4 }}
{{ end }}
---
{{ if (include "parsersIsNotEmpty" .) }}
{{- range $stage, $stageConfig := .Values.config.parsers -}}
{{- if $stageConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "crowdsec-parsers-%s" $stage }}
data:
{{ range $fileName, $content := $stageConfig -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
---
{{- end }}
{{ end }}
{{ end -}}

{{- if .Values.config.scenarios }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "crowdsec-scenarios"
data:
{{ range $fileName, $content := .Values.config.scenarios -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
{{- end }}

---
{{ if (include "postoverflowsIsNotEmpty" .) }}
{{- range $stage, $stageConfig := .Values.config.postoverflows -}}
{{- if $stageConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "crowdsec-postoverflows-%s" $stage }}
data:
{{ range $fileName, $content := $stageConfig -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
---
{{- end }}
{{ end }}
{{ end -}}

---
{{- if index .Values.config "agent_config.yaml.local" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-agent-config-local
data:
  config.yaml.local: |
{{ printf "%+v" (index .Values.config "agent_config.yaml.local") | indent 4 }}
{{- end }}

{{- end }}