# vim: set ft=gotmpl:
---

{{- if and (.Values.agent.metrics.enabled) (.Values.agent.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-agent-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-agent-service
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  endpoints:
    - port: metrics
{{ end }}
