# vim: set ft=gotmpl:
---

{{- if and (.Values.appsec.enabled) (.Values.appsec.metrics.enabled) (.Values.appsec.metrics.serviceMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-appsec-service
  namespace: {{ .Release.Namespace }}
  {{- if .Values.appsec.metrics.serviceMonitor.additionalLabels }}
  labels:
{{ toYaml .Values.appsec.metrics.serviceMonitor.additionalLabels | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-appsec-service
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  attachMetadata:
    node: true
  endpoints:
    - port: metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: machine
{{ end }}