{{- if .Values.appsec.enabled }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: appsec-acquis-config
data:
  acquis.yaml: |-
    {{- range .Values.appsec.acquisitions }}
    ---
    {{. | toYaml | nindent 4}}
    {{- end }}

---
{{ if (include "appsecParsersIsNotEmpty" .) }}
{{- range $stage, $stageConfig := .Values.appsec.parsers -}}
{{- if $stageConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "crowdsec-appsec-parsers-%s" $stage }}
data:
{{ range $fileName, $content := $stageConfig -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
---
{{- end }}
{{ end }}
{{ end -}}

---
{{- if .Values.appsec.scenarios }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "crowdsec-appsec-scenarios"
data:
{{ range $fileName, $content := .Values.appsec.scenarios -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
{{- end }}

---
{{- if .Values.appsec.contexts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "crowdsec-appsec-contexts"
data:
{{ range $fileName, $content := .Values.appsec.contexts -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
{{- end }}

---
{{ if (include "appsecPostoverflowsIsNotEmpty" .) }}
{{- range $stage, $stageConfig := .Values.appsec.postoverflows -}}
{{- if $stageConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "crowdsec-appsec-postoverflows-%s" $stage }}
data:
{{ range $fileName, $content := $stageConfig -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
---
{{- end }}
{{ end }}
{{ end -}}

---
{{- if .Values.appsec.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "crowdsec-appsec-configs"
data:
{{ range $fileName, $content := .Values.appsec.configs -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
{{- end }}

---
{{- if .Values.appsec.rules }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "crowdsec-appsec-rules"
data:
{{ range $fileName, $content := .Values.appsec.rules -}}
  {{ printf "%s: |" $fileName | indent 2 }}
{{ $content | indent 4 }}
{{ end }}
{{- end }}

---
{{- if index .Values.config "appsec_config.yaml.local" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: crowdsec-appsec-config-local
data:
  config.yaml.local: |
{{ printf "%+v" (index .Values.config "appsec_config.yaml.local") | indent 4 }}
{{- end }}

{{- end }}