{{- if .Values.appsec.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-appsec-service
  labels:
    app: {{ .Release.Name }}-appsec-service
    {{- with .Values.appsec.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.appsec.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.appsec.service.type }}
  {{- with .Values.appsec.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.appsec.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.appsec.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.appsec.service.type "LoadBalancer") (eq .Values.appsec.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.appsec.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if or (len .Values.appsec.acquisitions) (.Values.appsec.metrics.enabled) }}
  ports:
    {{- if .Values.appsec.metrics.enabled }}
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: metrics
    {{- end }}
    {{- range .Values.appsec.acquisitions }}
      {{- if and (hasKey . "listen_addr") (not startsWith "127.0.0.1" .listen_addr) }}
    {{- $listen_addr := .listen_addr | default "" }}
    {{- $url := printf "http://%s/" .listen_addr | urlParse }}
    {{- $port := .listen_addr | replace (printf "%s:" $url.hostname) "" }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: appsec{{ if ne $port "7422" }}-{{ $port }}{{ end }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    k8s-app: {{ .Release.Name }}
    type: appsec
    version: v1
{{- end }}