{{- if and (.Values.appsec.enabled) (.Values.appsec.metrics.enabled) (.Values.appsec.metrics.podMonitor.enabled) }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-appsec
  namespace: {{ .Release.Namespace }}
  {{- if .Values.appsec.metrics.podMonitor.additionalLabels }}
  labels:
{{ toYaml .Values.appsec.metrics.podMonitor.additionalLabels | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
      type: appsec
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  attachMetadata:
    node: true
  podMetricsEndpoints:
    - port: metrics
      relabelings:
      - action: replace
        sourceLabels:
        - __meta_kubernetes_pod_node_name
        targetLabel: machine
{{ end }}
