{{- if .Values.lapi.enabled }}
  {{- if not (eq (include "IsOnlineAPIDisabled" .) "true") }}
    {{- if eq (include "StoreCAPICredentialsInSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-capi-credentials
  labels:
    k8s-app: {{ .Release.Name }}
    type: capi-credentials-job
    version: v1
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-1"
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  online_api_credentials.yaml: |
    {{ printf "url: \"placeholder\"\nlogin: \"placeholder\"\npassword: \"placeholder\"" | b64enc }}
    {{- end }}
  {{- end }}
{{- end }}
