{{- if not (eq (include "IsOnlineAPIDisabled" .) "true") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-capi-credentials
  labels:
    k8s-app: {{ .Release.Name }}
    type: capi-credentials-job
    version: v1
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
data:
  online_api_credentials.yaml: |
    url: "placeholder"
    login: "placeholder"
    password: "placeholder"
{{- end }}