{{- if or (not .Values.tls.enabled) (not .Values.tls.appsec.tlsClientAuth) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }} 
  name: {{ .Release.Name }}-config
  labels:
    k8s-app: {{ .Release.Name }}
    type: config
    version: v1
rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "patch"]
{{- end }}