{{- if or (not .Values.tls.enabled) (not .Values.tls.appsec.tlsClientAuth) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-config
  labels:
    k8s-app: {{ .Release.Name }}
    type: config
    version: v1
{{- end }}