{{- if or (not .Values.tls.enabled) (not .Values.tls.appsec.tlsClientAuth) }}
{{- if not .Values.secrets.encryption.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-config
  labels:
    k8s-app: {{ .Release.Name }}
    type: config
    version: v1
type: Opaque
data:
  encryptionSecret: {{ include "config.encryptionSecretValue" . | b64enc }}
{{- end -}}
{{- end -}}