apiVersion: v1
kind: ConfigMap
metadata:
    name: crowdsec-docker-start-script-configmap
    labels:
        k8s-app: crowdsec
        type: docker-start-script
        version: v1

data:
    docker_start.sh: |-
{{ (.Files.Get "files/docker-start-custom.sh") | indent 8 }}