# vim: set ft=gotmpl:
---

{{- if .Values.lapi.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.lapi.ingress.annotations | nindent 4 }}
  name: {{ .Release.Namespace }}-lapi
  namespace: {{ .Release.Namespace }}
  labels:    
    {{- if .Values.lapi.ingress.labels }}    
    {{- toYaml .Values.lapi.ingress.labels | nindent 4 }}
    {{- else }}
    k8s-app: {{ .Release.Name }}
    type: lapi-api
    version: v1
    {{- end }}
spec:
  ingressClassName: {{ .Values.lapi.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.lapi.ingress.host }}
      http:
        paths:
          - path: {{ .Values.lapi.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 8080
  {{- if .Values.lapi.ingress.tls }}
  tls:
    {{- tpl (toYaml .Values.lapi.ingress.tls | nindent 4) . }}
  {{- end -}}
{{- end -}}
