# vim: set ft=gotmpl:
---

apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
type: Opaque
data:
  csLapiSecret: {{ quote .Values.lapi.secrets.csLapiSecret }}
  registrationToken: {{ quote .Values.lapi.secrets.registrationToken }}
  {{- with .Values.lapi.extraSecrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}