{{- if or (not .Values.secrets.externalSecret.name) .Values.lapi.extraSecrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-lapi-secrets
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
type: Opaque
data:
{{- if not .Values.secrets.externalSecret.name }}
  csLapiSecret: {{ include "lapi.csLapiSecret" . | b64enc }}
  registrationToken: {{ include "lapi.registrationToken" . | b64enc }}
{{- end }}
  {{- with .Values.lapi.extraSecrets }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
{{- end -}}