# vim: set ft=gotmpl:
---

apiVersion: v1
kind: Secret
metadata:
  name: agent-credentials
  labels:
    k8s-app: {{ .Release.Name }}
    type: lapi
    version: v1
type: Opaque
data:
  username: {{ include "agent.username" . | b64enc }}
  password: {{ include "agent.password" . | b64enc }}
