{{ if and (.Values.agent.enabled) (.Values.tls.enabled) (.Values.tls.certManager.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-agent
  namespace: {{ .Release.Namespace }}
spec:
  commonName: CrowdSec Agent
  secretName: {{ .Release.Name }}-agent-tls
  duration: {{ .Values.tls.certManager.duration }}
  renewBefore: {{ .Values.tls.certManager.renewBefore }}
  secretTemplate:
    {{ if or .Values.tls.agent.reflector.namespaces .Values.tls.certManager.secretTemplate.annotations }}
    annotations:
      {{ if .Values.tls.agent.reflector.namespaces }}
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ join "," .Values.tls.agent.reflector.namespaces }}
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      {{ end }}
      {{ if .Values.tls.certManager.secretTemplate.annotations }}
      {{ toYaml .Values.tls.certManager.secretTemplate.annotations | nindent 6 }}
      {{ end }}
    {{ end }}
    {{ if .Values.tls.certManager.secretTemplate.labels }}
    labels:
    {{ toYaml .Values.tls.certManager.secretTemplate.labels | nindent 6 }}
    {{ end }}
  issuerRef:
    {{ if .Values.tls.certManager.issuerRef }}
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ default "Issuer" .Values.tls.certManager.issuerRef.kind }}
    {{ else }}
    name: {{ .Release.Name }}-ca-issuer
    {{ end }}
  subject:
    organizationalUnits:
      - agent-ou
{{ end }}
