# vim: set ft=gotmpl:
---
{{ if and (.Values.tls.enabled) (.Values.tls.certManager.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  commonName: CrowdSec Bouncer
  secretName: {{ .Release.Name }}-bouncer-tls
  duration: {{ .Values.tls.certManager.duration }}
  renewBefore: {{ .Values.tls.certManager.renewBefore }}
  secretTemplate:
    annotations:
      {{ if .Values.tls.bouncer.reflector.namespaces }}
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ join "," .Values.tls.bouncer.reflector.namespaces }}
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      {{ end }}
  issuerRef:
    {{ if .Values.tls.certManager.issuerRef }}
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ default "Issuer" .Values.tls.certManager.issuerRef.kind }}
    {{ else }}
    name: {{ .Release.Name }}-ca-issuer
    {{ end }}
  subject:
    organizationalUnits:
      - bouncer-ou
{{ end }}
