# vim: set ft=gotmpl:
---
{{ if and (.Values.tls.enabled) (.Values.tls.certManager.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-bouncer
  namespace: {{ .Release.Namespace }}
spec:
  commonName: CrowdSec Bouncer
  secretName: {{ .Release.Name }}-bouncer-tls
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
  subject:
    organizationalUnits:
      - bouncer-ou
{{ end }}
