{{ if and (.Values.tls.enabled) (.Values.tls.certManager.enabled) (not .Values.tls.certManager.issuerRef) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ .Release.Name }}-ca
  secretName: {{ .Release.Name }}-root-secret
  {{- with .Values.tls.certManager.ca.duration }}
  duration: {{ . }}
  {{- end }}
  {{- with .Values.tls.certManager.ca.renewBefore }}
  renewBefore: {{ . }}
  {{- end }}
  privateKey:
    algorithm: ECDSA
    size: 256
    {{- with .Values.tls.certManager.ca.rotationPolicy }}
    rotationPolicy: {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Release.Name }}-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{ end }}
