# vim: set ft=gotmpl:
---
{{ if and (.Values.tls.enabled) (.Values.tls.certManager.enabled) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-lapi
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Release.Name }}-service.{{ .Release.Namespace }}
    - {{ .Release.Name }}-service.{{ .Release.Namespace }}.svc.cluster.local
    - localhost
  secretName: {{ .Release.Name }}-lapi-tls
  duration: {{ .Values.tls.certManager.duration }}
  renewBefore: {{ .Values.tls.certManager.renewBefore }}
  issuerRef:
    {{ if .Values.tls.certManager.issuerRef }}
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ default "Issuer" .Values.tls.certManager.issuerRef.kind }}
    {{ else }}
    name: {{ .Release.Name }}-ca-issuer
    {{ end }}
  {{ if or .Values.tls.certManager.secretTemplate.annotations .Values.tls.certManager.secretTemplate.labels }}
  secretTemplate:
    {{ if .Values.tls.certManager.secretTemplate.annotations }}
    annotations:
    {{ toYaml .Values.tls.certManager.secretTemplate.annotations | nindent 6 }}
    {{ end }}
    {{ if .Values.tls.certManager.secretTemplate.labels }}
    labels:
    {{ toYaml .Values.tls.certManager.secretTemplate.labels | nindent 6 }}
    {{ end }}
  {{ end }}
{{ end }}
