{{- if .Values.agent.enabled }}
{{- $ports := include "crowdsec.logProcessor.ports" (dict "values" .Values.agent) | fromYamlArray }}
{{- include "crowdsec.service" (dict "ctx" . "component" "agent" "values" .Values.agent "ports" $ports) }}
{{- with (include "crowdsec.serviceMonitor" (dict "ctx" . "component" "agent" "values" .Values.agent)) }}
---
{{- . }}
{{- end }}
{{- end }}
