name: Update docs

on:
  push:
    branches:
      - main
    paths:
      - 'charts/*/values.yaml'
      - 'charts/*/Chart.yaml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run helm-docs
        run: |
          GOBIN=$PWD go install github.com/norwoodj/helm-docs/cmd/helm-docs@v1.11.0
          ./helm-docs --sort-values-order file
          rm helm-docs

      - name: Commit bump
        uses: EndBug/add-and-commit@v9
        with:
            branch: ${{ github.event.pull_request.base.ref }}
            message: 'Regenerate chart README.md'
